### ISSUE TITLE
did you compared performance with SVR 

### ISSUE THREAD

**Issue by Sandy4321** [msangnier/qreg#5]
did you compared performance with SVR 
https://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVR.html#sklearn.svm.LinearSVR

**Comment by Sandy4321** [comment]
1
yes I see
https://github.com/msangnier/qreg/blob/master/examples/svr.py
but it is not LinearSVR

since 
LinearSVR
is used for big spars data
and your code as written should be good especially for  sparse data 
2
by the way 
what you mean under 
sparse data

is it data after one hot for categorical data , as well?

**Comment by msangnier** [comment]
We didn't compare to LinearSVR. It performs very well in practice, certainly better than qreg for linear SVR.

**Comment by Sandy4321** [comment]
great thanks for soon answer
very kind of you to help
"It performs very well in practice, certainly better than qreg for linear SVR."
do you mean 
https://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVR.html
is faster
or 
provides better performance?
my guess qreg and sklearn LinearSVR should provide same performance for qreg  liner kernel

**Comment by msangnier** [comment]
LinearSVR is probably faster but both should provide the same accuracy.

**Comment by Sandy4321** [comment]
thanks for soon answer 
"LinearSVR is probably faster but both should provide the same accuracy"

only one clarification please
your code is not support vector regression
then your decision boundary is very different than 
https://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVR.html

therefore,  how it can be that your code providing  the same accuracy as LinearSVR

Though, https://github.com/liquidSVM/liquidSVM could provide the same accuracy as  sklearn LinearSVR.htm
but liquidSVM  does  not have linear kernel...

**Comment by msangnier** [comment]
Just use kernel='linear' in qreg.

**Comment by Sandy4321** [comment]
great
then I used data generating inspired by 
https://github.com/lazyprogrammer/machine_learning_examples/blob/master/linear_regression_class/l1_regularization.py

and got strange results
code is 
___________________________________________________________________
``
import numpy as np
import matplotlib.pyplot as plt


from sklearn.preprocessing import StandardScaler


additive_noise = 1 #2 #3 #0.5
N = 150 #180 #100 #180 #170 #160 #150 #140 #130 #200 #100 #500
D = 10 #50

# uniformly distributed numbers between -5, +5
X = (np.random.random((N, D)) - 0.5)*10

scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)


true_w = np.array([1, 0.5, -0.5, 0.7, -0.3, 0.2, 0.4, -0.6, 1.2, -0.9] )

# generate Y - add noise
Y = X.dot(true_w) + np.random.randn(N) * additive_noise


from qreg import QRegressor
probs = np.linspace(0.1, 0.9, 5)

# Define the quantile regressor
#Just use kernel='linear' in qreg.
reg = QRegressor(kernel='linear',
                 C=1e2,  # Trade-off parameter
                 probs=probs,  # Quantile levels
                 gamma_out=1e-2,  # Inner kernel parameter
                 eps=2,  # Epsilon-loss level
                 alg='sdca',  # Algorithm (can change to 'qp')
                 max_iter=1e4,  # Maximal number of iteration
                 active_set=True,  # Active set strategy
                 verbose=True)

# Fit on training data and predict on test data
reg.fit(X, Y)  #This is the same as in scikit-learn: reg.fit(X, y)
pred = reg.predict(X)

plt.figure(figsize=(7, 5))
plt.plot(Y,Y, '.b', label='true Y')
plt.plot(Y,pred[0], '.r',label='estimated -> pred[0] ')
plt.plot(Y,pred[1], '.m',label='estimated -> pred[1] ')
plt.plot(Y,pred[2], '.g',label='estimated -> pred[2] ')
plt.plot(Y,pred[3], '.c',label='estimated -> pred[3] ')
plt.plot(Y,pred[4], '.k',label='estimated -> pred[4] ')
plt.legend()
plt.show(block = False)


plt.figure(figsize=(7, 5))
plt.plot(Y, 'b', label='true Y')
plt.plot(pred[0], 'r',label='estimated -> pred[0] ')
plt.plot(pred[1], 'm',label='estimated -> pred[1] ')
plt.plot(pred[2], 'g',label='estimated -> pred[2] ')
plt.plot(pred[3], 'c',label='estimated -> pred[3] ')
plt.plot(pred[4], 'k',label='estimated -> pred[4] ')
plt.legend()
plt.show(block = False)
q=0
``
__________________________________________________________
results are


![image](https://user-images.githubusercontent.com/11426119/121821016-0bb2df80-cc64-11eb-9f2a-18df2b484e74.png)


and

![image](https://user-images.githubusercontent.com/11426119/121821025-21c0a000-cc64-11eb-9ad7-a76270a7ce15.png)

**Comment by Sandy4321** [comment]
any updates why your code is not working for spars data ?

or I did mistake somewhere in code ?

**Comment by msangnier** [comment]
Not sure the code is no working;

1. You should plot Y versus X.
2. Use the QP solver for a safe estimation.

**Comment by Sandy4321** [comment]
can you share full example pls
with data above ?

**Comment by Sandy4321** [comment]
reg = QRegressor(kernel='linear',
C=1e2, # Trade-off parameter
probs=probs, # Quantile levels
gamma_out=1e-2, # Inner kernel parameter
eps=2, # Epsilon-loss level
alg='sdca', # Algorithm (can change to 'qp')
max_iter=1e4, # Maximal number of iteration
active_set=True, # Active set strategy
verbose=True)

where to put 
QP solver for a safe estimation??

**Comment by Sandy4321** [comment]
changed to qp 

    reg = QRegressor(kernel='linear',
    C=1e2, # Trade-off parameter
    probs=probs, # Quantile levels
    gamma_out=1e-2, # Inner kernel parameter
    eps=2, # Epsilon-loss level
    alg='qp', # Algorithm (can change to 'qp')
    max_iter=1e4, # Maximal number of iteration
    active_set=True, # Active set strategy
    verbose=True)

get the same bad results

**Comment by Sandy4321** [comment]
you can try new code by yourself 

'''
#https://github.com/msangnier/qreg/issues/5#issuecomment-936289475
#https://github.com/lazyprogrammer/machine_learning_examples/blob/master/linear_regression_class/l1_regularization.py

import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler

additive_noise = 1 #2 #3 #0.5
N = 150 #180 #100 #180 #170 #160 #150 #140 #130 #200 #100 #500
D = 10 #50

#uniformly distributed numbers between -5, +5
X = (np.random.random((N, D)) - 0.5)*10

scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

true_w = np.array([1, 0.5, -0.5, 0.7, -0.3, 0.2, 0.4, -0.6, 1.2, -0.9] )

#generate Y - add noise
Y = X.dot(true_w) + np.random.randn(N) * additive_noise

from qreg import QRegressor
probs = np.linspace(0.1, 0.9, 5)

#Define the quantile regressor
#Just use kernel='linear' in qreg.

if 1:
    reg = QRegressor(kernel='linear',
    C=1e2, # Trade-off parameter
    probs=probs, # Quantile levels
    gamma_out=1e-2, # Inner kernel parameter
    eps=2, # Epsilon-loss level
    alg='qp', # Algorithm (can change to 'qp')
    max_iter=1e4, # Maximal number of iteration
    active_set=True, # Active set strategy
    verbose=True)
else:
    reg = QRegressor(kernel='linear',
    C=1e2, # Trade-off parameter
    probs=probs, # Quantile levels
    gamma_out=1e-2, # Inner kernel parameter
    eps=2, # Epsilon-loss level
    alg='sdca', # Algorithm (can change to 'qp')
    max_iter=1e4, # Maximal number of iteration
    active_set=True, # Active set strategy
    verbose=True)    

#Fit on training data and predict on test data
reg.fit(X, Y) #This is the same as in scikit-learn: reg.fit(X, y)
pred = reg.predict(X)

plt.figure(figsize=(7, 5))
plt.plot(Y,Y, '.b', label='true Y')
plt.plot(Y,pred[0], 'xr',label='estimated -> pred[0] ')
plt.plot(Y,pred[1], '.m',label='estimated -> pred[1] ')
plt.plot(Y,pred[2], '.g',label='estimated -> pred[2] ')
plt.plot(Y,pred[3], '.c',label='estimated -> pred[3] ')
plt.plot(Y,pred[4], '*k',label='estimated -> pred[4] ')
plt.xlabel('actual data')
plt.ylabel('predicted  values')
plt.legend()
plt.show(block = False)

plt.figure(figsize=(7, 5))
plt.plot(Y, 'b', label='true Y')
plt.plot(pred[0], 'r',label='estimated -> pred[0] ')
plt.plot(pred[1], 'm',label='estimated -> pred[1] ')
plt.plot(pred[2], 'g',label='estimated -> pred[2] ')
plt.plot(pred[3], 'c',label='estimated -> pred[3] ')
plt.plot(pred[4], 'k',label='estimated -> pred[4] ')
plt.xlabel('data sample number ')
plt.ylabel('predicted  values')
plt.legend()
plt.show(block = False)
q=0

'''

**Comment by msangnier** [comment]
You should try with D=1 and plot Y versus X, pred[0] versus X, and so on.

**Comment by Sandy4321** [comment]
plot Y versus X, pred[0] versus X

it is in code above
plt.figure(figsize=(7, 5))
plt.plot(Y,Y, '.b', label='true Y')
plt.plot(Y,pred[0], 'xr',label='estimated -> pred[0] ')
plt.plot(Y,pred[1], '.m',label='estimated -> pred[1] ')
plt.plot(Y,pred[2], '.g',label='estimated -> pred[2] ')
plt.plot(Y,pred[3], '.c',label='estimated -> pred[3] ')
plt.plot(Y,pred[4], '*k',label='estimated -> pred[4] ')
plt.xlabel('actual data')
plt.ylabel('predicted values')
plt.legend()
plt.show(block = False)


also see first plot on this page?

**Comment by Sandy4321** [comment]
why to limit D=1
even in your examples is see 2 dimensional data?
z = toy_data(10)
z[0]
array([0.0126824 , 0.01359056, 0.14384791, 0.31195618, 0.32142393,
       0.60303202, 0.63191561, 0.7108509 , 0.81217872, 1.12113393])
z[1]
array([-0.51436997,  1.82866818,  0.48069505, -1.57633519, -1.20058447,
        0.28901787,  1.01525003,  1.84298933,  1.69947138, -1.75979931])
type(z)
<class 'tuple'>
len(z)
3
z[2]
[array([-0.08171567, -0.08771558, -1.01884352, -1.48756032, -1.46272747,
        1.17783467,  1.45188053,  1.93653931,  1.84147081, -1.18136442])]
z[3]
Traceback (most recent call last):
  Debug Console, prompt 9, line 1
builtins.IndexError: tuple index out of range

**Comment by Sandy4321** [comment]
I tested all your examples
x_train, y_train, z_train = toy_data(50)

but z_train is never used
what is it?

**Comment by Sandy4321** [comment]
in short , from your answer above follows your code is only for one dimensional data ?

**Comment by msangnier** [comment]
I am not sure to be the right person to debug your code (as I am not sure this is the right place to do it) or to explain you the method. I suggest your read the paper associated to the code, as well as the documentation. If you have questions, could you ask someone closer?

To answer your questions:

1. the method does work for multidimensional data but if you want plots, you have to use unidimensional data (2D data for 3D plots) and plot Y versus X. For instance (examples/algorithms.py):
plt.plot(x_train, y_train, '.')
    for q in pred:
        plt.plot(x_test, q, '-')
    for q in z_test:
        plt.plot(x_test, q, '--')
    plt.title('Operator-valued kernel')

2. for z_train, please, read the documentation:
def toy_data(n=50, t_min=0., t_max=1.5, noise=1., probs=[0.5]):
    """
    Parameters
    n: number of points (t, y)
    t_min: minimum input data t
    t_max: maximum input data t
    noise: noise level
    probs: probabilities (quantiles levels)
    Returns:
    x: sorted random data in [t_min, t_max]
    y: targets corresponding to x (following a noisy sin curve)
    q: true quantiles corresponding to x

**Comment by Sandy4321** [comment]
great can then share full example from 0 to end example for 2D data

for example for this toy data
additive_noise = 1 #2 #3 #0.5
N = 150 
D = 10 

uniformly distributed numbers between -5, +5
X = (np.random.random((N, D)) - 0.5)*10

scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

true_w = np.array([1, 0.5, -0.5, 0.7, -0.3, 0.2, 0.4, -0.6, 1.2, -0.9] )

generate Y - add noise
Y = X.dot(true_w) + np.random.randn(N) * additive_noise
