### ISSUE TITLE
do you have examples for tabular data

### ISSUE THREAD

**Issue by Sandy4321** [msangnier/qreg#9]
do you have examples for tabular data
since I see in your code only for one dimension x 
like
x1          x2         x3     y
0.5       -0.3       0.2     1.5
-0.9     0.1        -0.4     0.2
1.4       3.7       -9.4     -3.5

etc?

https://github.com/liquidSVM has it
https://github.com/liquidSVM/liquidSVM/tree/master/data

**Comment by msangnier** [comment]
This is the same as in scikit-learn: reg.fit(X, y).
